SELECT "This is SQL Exercise, Practice and Solution";
SELECT 1, 2, 3;
SELECT 10 + 15;
SELECT 10 * 15;
SELECT * FROM Scientists;
SELECT * FROM Projects;
SELECT Name AS 'Nome do Projeto', Hours AS 'Tempo de Trabalho' FROM Projects;
SELECT Name FROM Scientists ORDER BY name;
SELECT Name FROM Projects ORDER BY name DESC;
SELECT CONCAT('O projeto ', Name, ' precisou de ', Hours, ' horas para ser concluído.') FROM Projects;
SELECT * FROM Projects ORDER BY Hours DESC LIMIT 3;
SELECT * FROM AssignedTo;
SELECT DISTINCT Project FROM AssignedTo;
SELECT Name FROM Projects ORDER BY Hours DESC LIMIT 1;
SELECT Name FROM Projects ORDER BY Hours DESC LIMIT 1 OFFSET 1;
SELECT * FROM Projects ORDER BY Hours LIMIT 5;
SELECT CONCAT('Existem ', COUNT(SSN), ' cientistas na tabela Scientists.') FROM Scientists;